version: '3.8'

services:
  # 后端服务
  life-rpg-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: life-rpg-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql01
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=life_rpg
    networks:
      - life-rpg-network

  # 前端服务
  life-rpg-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: life-rpg-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - life-rpg-backend
    networks:
      - life-rpg-network

networks:
  life-rpg-network:
    driver: bridge
